name: ZMagicGuilds
version: '${project.version}'
main: com.zennyel.GuildsPlugin
api-version: 1.8
commands:
  guild:
    description: "main command for this plugin"
  party:
    description: "party commands!"
  adventurer:
    description: "adventurer management"
softdepend: [Z_Magic, Boss]