name: ZMagicGuilds
version: '${project.version}'
main: com.zennyel.GuildsPlugin
api-version: 1.8
permissions:
  zmagic.use:
    description: "basic permission"
commands:
  guilds:
    description: "main command for this plugin"
softdepend: [Z_Magic]